In [1]:
import numpy as np

# csv数据的加载

In [2]:
filename = './data/presidential_polls.csv'
data_arr = np.loadtxt(filename,# 加载的外部文件的名称
                       delimiter=',', # 文件分隔符
                       #skiprows =1, # 设定跳过的行数
                       dtype=str, # 数据类型为字符串类型
                       usecols = (3,17,18,19) # 指定要加载的列的索引                       
                      )

In [3]:
print(data_arr)
print(type(data_arr))

[['matchup' 'adjpoll_clinton' 'adjpoll_trump' 'adjpoll_johnson']
 ['"Clinton vs. Trump vs. Johnson"' '42.6414' '40.86509' '5.675099']
 ['"Clinton vs. Trump vs. Johnson"' '43.29659' '44.72984' '3.401513']
 ...
 ['"Clinton vs. Trump vs. Johnson"' '45.9713' '39.97518' '']
 ['"Clinton vs. Trump vs. Johnson"' '45.2939' '46.66175' '1.596946']
 ['"Clinton vs. Trump vs. Johnson"' '31.62721' '44.65947' '']]
<class 'numpy.ndarray'>


# nadarray属性

In [4]:
print('维度个数：',data_arr.ndim)
print('维度大小：',data_arr.shape)
print('数据类型：',data_arr.dtype)

维度个数： 2
维度大小： (10237, 4)
数据类型： <U31


In [5]:
data_arr = np.genfromtxt(filename, # 文件名称
                         delimiter=',', #文件分隔符
                         dtype = str,# 数据类型
                         usecols = (3,17,18,19) #指定加载列的索引
                        )

In [6]:
print(data_arr)

[['matchup' 'adjpoll_clinton' 'adjpoll_trump' 'adjpoll_johnson']
 ['"Clinton vs. Trump vs. Johnson"' '42.6414' '40.86509' '5.675099']
 ['"Clinton vs. Trump vs. Johnson"' '43.29659' '44.72984' '3.401513']
 ...
 ['"Clinton vs. Trump vs. Johnson"' '45.9713' '39.97518' '']
 ['"Clinton vs. Trump vs. Johnson"' '45.2939' '46.66175' '1.596946']
 ['"Clinton vs. Trump vs. Johnson"' '31.62721' '44.65947' '']]


# 随机ndarray创建

In [7]:
arr = np.random.rand(3,4)
print(arr)
print(type(arr))

[[0.33143092 0.64787879 0.77862463 0.09342747]
 [0.64778631 0.98999758 0.84105579 0.95500869]
 [0.68706854 0.44729499 0.28933953 0.46495526]]
<class 'numpy.ndarray'>


In [8]:
arr = np.random.randn(3,4)
print(arr)

[[-0.0873181  -0.64333218  0.47159441 -0.51208466]
 [-1.50038613  0.56638212 -0.36171518 -0.81534537]
 [ 1.13699823  2.44380336 -1.07339622 -0.23555107]]


# 随机整数数组的创建

In [9]:
arr = np.random.randint(-1,5,size=(3,4))
print(arr)
print(arr.dtype)

[[ 2  4  4 -1]
 [ 2  4  0  3]
 [-1  2  2  0]]
int32


# 随机浮点型数组的创建

In [10]:
arr = np.random.uniform(-1,5,size=(3,4))
print(arr)

[[-0.04022386  0.53610959  3.93668297  3.55409781]
 [ 3.37968083 -0.04499401  3.83549204  1.22231802]
 [ 1.24258144  2.28466898  4.27732212  3.33309329]]


# 创建全1的数组


In [11]:
arr_ones = np.ones((3,4))
print(arr_ones)
print(arr_ones.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64


# 创建全0数组


In [12]:
arr_zeros = np.zeros((3,4))
print(arr_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# python list ==>numpy ndarray

In [13]:
ls = range(10)
arr = np.array(ls)
print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
1


# 嵌套列表装换为ndarray

In [14]:
ls = [range(10),range(10)]
arr = np.array(ls)
print(arr)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


# ndarray ==> list

In [15]:
ls  = arr.tolist()
print(ls)
print(type(ls))

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]
<class 'list'>


# 调整数组的维数

In [16]:
arr = np.arange(16)
print(arr)
print(type(arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
<class 'numpy.ndarray'>


In [17]:
print(arr.reshape(4,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [18]:
print(arr.reshape(2,2,4))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [19]:
print(arr.reshape(2,2,2,2))

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [20]:
print(arr.reshape(2,2,2,2,1))

[[[[[ 0]
    [ 1]]

   [[ 2]
    [ 3]]]


  [[[ 4]
    [ 5]]

   [[ 6]
    [ 7]]]]



 [[[[ 8]
    [ 9]]

   [[10]
    [11]]]


  [[[12]
    [13]]

   [[14]
    [15]]]]]


# 指定数组的数据类型

In [21]:
zero_float_arr = np.zeros((3,4),dtype=np.float64)
print(zero_float_arr)
print(zero_float_arr.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [22]:
zero_int_arr = np.zeros((3,4),dtype=np.int32)
print(zero_int_arr)
print(zero_int_arr.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


# astype（）数据类型转换

In [23]:
print(zero_float_arr)
zero_int_arr_2 = zero_float_arr.astype(np.int32)
print(zero_int_arr_2)
print(zero_int_arr_2.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


# 一维数组的索引与切片

In [24]:
arr1 = np.arange(10)
print(arr1)
print(arr1[3])
print(arr1[4])
print(arr1[2:6])
print(arr1[:5])
print(arr1[3:])

[0 1 2 3 4 5 6 7 8 9]
3
4
[2 3 4 5]
[0 1 2 3 4]
[3 4 5 6 7 8 9]


# 多维数组的索引与切片

In [25]:
arr2 = np.arange(12).reshape(3,4)
print(arr2)
print(arr2[1])
print(arr2[1,2])
print(arr2[0:2,1:3])
print(arr2[:,1:3])
print(arr2[0:2,:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
6
[[1 2]
 [5 6]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[0 1 2 3]
 [4 5 6 7]]


# 条件索引

In [26]:
year_arr = np.array([[2000,2001,2003],[2005,2003,2008],[2001,2003,2010]])
print(year_arr)

[[2000 2001 2003]
 [2005 2003 2008]
 [2001 2003 2010]]


In [27]:
bool_arr = year_arr >= 2005
print(bool_arr)
print(bool_arr.dtype)
print(year_arr.ndim,bool_arr.ndim)
print(year_arr.shape,bool_arr.shape)
print(year_arr[bool_arr])

[[False False False]
 [ True False  True]
 [False False  True]]
bool
2 2
(3, 3) (3, 3)
[2005 2008 2010]


In [28]:
data_arr = np.random.randn(3,3)
print(data_arr)

[[ 2.16822329 -0.90691252 -0.49558986]
 [ 0.20154505 -0.58072398  0.20795632]
 [ 0.09522698 -1.28836072  0.37367936]]


In [29]:
print(data_arr[bool_arr])

[0.20154505 0.20795632 0.37367936]


# 元素计算函数

In [30]:
arr = np.random.randn(2,3)
print(arr)

[[-1.08742586  1.3212366   0.45895624]
 [ 0.36783673  0.71915089  0.62917758]]


In [31]:
print(np.ceil(arr))

[[-1.  2.  1.]
 [ 1.  1.  1.]]


In [32]:
print(np.floor(arr))

[[-2.  1.  0.]
 [ 0.  0.  0.]]


In [33]:
print(np.rint(arr))

[[-1.  1.  0.]
 [ 0.  1.  1.]]


In [34]:
print(np.isnan(arr))

[[False False False]
 [False False False]]


In [35]:
print(arr)
print(np.multiply(arr,arr))

[[-1.08742586  1.3212366   0.45895624]
 [ 0.36783673  0.71915089  0.62917758]]
[[1.18249501 1.74566615 0.21064083]
 [0.13530386 0.517178   0.39586442]]


In [36]:
print(np.divide(arr,arr))

[[1. 1. 1.]
 [1. 1. 1.]]


In [37]:
print(np.where(arr>0,1,-1))

[[-1  1  1]
 [ 1  1  1]]


# 元素统计函数

In [38]:
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
print(np.sum(arr))
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

66
[12 15 18 21]
[ 6 22 38]


In [41]:
print(np.mean(arr))

5.5


In [43]:
arr = np.random.randint(0,10,(3,4))
print(arr)

[[1 4 7 8]
 [3 2 0 6]
 [5 3 3 3]]


In [46]:
print(np.max(arr))
print(np.min(arr))

8
0


In [48]:
print(np.max(arr,axis=0))
print(np.min(arr,axis=1))

[5 4 7 8]
[1 0 3]


In [50]:
print(np.var(arr))
print(np.std(arr))

5.1875
2.277608394786075


In [51]:
print(np.var(arr,axis=0))
print(np.std(arr,axis=1))

[2.66666667 0.66666667 8.22222222 4.22222222]
[2.73861279 2.16506351 0.8660254 ]


In [52]:
print(arr)
print(np.cumsum(arr))
print(np.cumprod(arr))

[[1 4 7 8]
 [3 2 0 6]
 [5 3 3 3]]
[ 1  5 12 20 23 25 25 31 36 39 42 45]
[   1    4   28  224  672 1344    0    0    0    0    0    0]


# 元素判断函数


In [53]:
arr = np.random.randn(2,3)
print(arr)

[[ 2.15067752 -0.71802329 -2.59868162]
 [-0.49925552  1.43221653 -1.03853216]]


In [54]:
print(np.any(arr>0))

True


In [55]:
print(np.all(arr>0))

False


# 元素去重排序

In [56]:
arr = np.array([[1,2,1],[2,3,4]])
print(arr)

[[1 2 1]
 [2 3 4]]


In [57]:
print(np.unique(arr))

[1 2 3 4]
